spring:
  config:
    activate:
      on-profile: "prod"
server:
  address: 127.0.0.1
  port: 8080

---
spring:
  config:
    activate:
      on-profile: "prodDB"

  datasource:
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false

logging:
  level:
    org.hibernate.sql: warn

---
spring:
  config:
    activate:
      on-profile: "prodS3"
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
storage:
  s3:
    base-prefix: prod/

---
spring:
  config:
    activate:
      on-profile: "prodSecret"

secret:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-access-expired-in: 7200000  # 2h
  jwt-refresh-expired-in: 5184000000  # 60d
---
