spring:
  config:
    activate:
      on-profile: "dev"
server:
  address: 127.0.0.1
  port: 8081

---
spring:
  config:
    activate:
      on-profile: "devDB"

  datasource:
    url: ${DATASOURCE_URL_DEV}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: "devS3"
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
storage:
  s3:
    base-prefix: dev/

---
spring:
  config:
    activate:
      on-profile: "devSecret"

secret:

  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-access-expired-in: 7200000
  jwt-refresh-expired-in: 5184000000
---
