spring:
  profiles:
    group:
      "local": "localDB, localS3, localSecret"
      "dev": "devDB, devS3, devSecret"
      "prod": "prodDB, prodS3, prodSecret"
---

server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    s3:
      bucket: rikubucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

---
season:
  start-date: 2025-09-01   # KST 기준